baseURL = "https://nouchka.katagena.com/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Jean-Avit Promis - Actual life and death I've given up on that."
theme = "hugo-tranquilpeak-theme"
canonifyurls = true
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
  disableAliases = false
  pagerSize = 7
  path = 'page'

[permalinks]
  post = "/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"

[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"

[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"

[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"

[[menu.main]]
  weight = 5
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-github\"></i>"
  url = "https://github.com/nouchka"

[[menu.links]]
  weight = 2
  identifier = "resume"
  name = "Resume"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-male\"></i>"
  url = "https://japromis.katagena.com/"

[[menu.links]]
  weight = 3
  identifier = "linkedin"
  name = "Linkedin"
  pre = "<i class=\"sidebar-button-icon fab fa-linkedin\"></i>"
  url = "https://fr.linkedin.com/in/japromis"

[[menu.links]]
  weight = 4
  identifier = "firefox"
  name = "I Use Firefox"
  pre = "<i class=\"sidebar-button-icon fab fa-firefox\"></i>"
  url = "https://www.mozilla.org/firefox/this-browser-comes-highly-recommended/?utm_source=devs-for.firefox.com&utm_medium=referral&utm_campaign=devs-for-firefox&utm_content=I-Use-Firefox"

[[menu.links]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"

[params]
  keywords = ["devops", "it"]
  description = "The blog of Jean-Avit Promis"
  syntaxHighlighter = "highlight.js"
  clearReading = true
  hierarchicalCategories = true
  sidebarBehavior = 1
  coverImage = "img/cover.webp"
  favicon = "/img/favicon.ico"
  imageGallery = true
  thumbnailImage = true
  thumbnailImagePosition = "bottom"
  autoThumbnailImage = true

  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"

  [params.author]
    name = "Jean-Avit Promis"
    bio = "OpenSource Enthousiast"
    job = "Coop√©rateur chez Coop'Alpha"
    location = "France"
    picture = "https://www.gravatar.com/avatar/780301ebabb8f3afd04835e64bbc45a4?s=110"

[module]
[[module.imports]]
  path = 'github.com/hugomods/images'
